### ISSUE TITLE
d.ontun.es/Login with Spotify doesn't work

### ISSUE THREAD

**Issue by n-99** [atj/userscripts#137]
On first use, I get a screen from d.ontun.es telling me to login to Spoitfy and letting it have access to my profile. It never gets added to Spotify, and I'm stuck on that screen.

**Comment by n-99** [comment]
Firefox 114.0b9 64-bit with uBlock Origin and Privacy Badger, but I shut those addons off and it didn't change anything.

**Comment by atj** [comment]
Apologies for the lack of updates. I'm going to close this issue as unfortunately d.ontun.es is dead.
