### ISSUE TITLE
Should remix userscript use edit relationship for recordings marked as edit, e.g. `radio edit`?

### ISSUE THREAD

**Issue by gustavkj** [atj/userscripts#183]
I'm wondering if it would make sense to make the remix userscript handle edits recordings named as `radio edit`? The [styleguide for recordings ](https://musicbrainz.org/doc/Style/Recording#Edits)suggests that, and in that case the [_editor_ role](https://musicbrainz.org/relationship/40dff87a-e475-4aa6-b615-9935b564d756) could be used for the [_remixer_ role](https://musicbrainz.org/relationship/7950be4d-13a3-48e7-906b-5af562e39544). 

It could also be an idea just to cover some of the most common kinds of edits, e.g. `radio edit`, `extended edit`, since these kinds do not have a specific remixer/editor.

What do you think?

**Comment by atj** [comment]
@gustavkj: Could you test the new version of the userscript in the `add-edit-of-links` branch please?

https://github.com/atj/userscripts/raw/add-edit-of-links/mb_add_remix_credit_links.user.js

You can see some example edit titles in the comment above the new regular expression:

https://github.com/atj/userscripts/blob/2dedcea19ffd23e3704ad8e924d1afbdc2423aad/mb_add_remix_credit_links.user.js#L35-L46

When the regex matches the new _Add "edit of" credit_ link is clickable. I've performed some limited testing and it seems to work as expected, e.g.

https://musicbrainz.org/release/276155ed-4623-4124-bb09-4f4f930bcaab/edit-relationships

**Comment by gustavkj** [comment]
Nice! It works on most cases I found. But I found an example where it does not work: https://musicbrainz.org/release/40921bf7-4c7d-4107-ab9f-6872c82c8330

The title structure `Flux (extended 12″ mix)` is a bit different, but similar to what you accounted for.

**Comment by atj** [comment]
> The title structure `Flux (extended 12″ mix)` is a bit different, but similar to what you accounted for.

Thanks, I knew I'd miss some variations. I've updated the regex and it matches `extended 12″ mix` now. If you could update the script once more and confirm it works for you I will release the new version.

**Comment by gustavkj** [comment]
Looks good! 👍 Just one additional, maybe also cover `club edit`? E.g. https://musicbrainz.org/release/06e6dab3-7248-4875-9a0d-dd329d970899

But apart from that, I think this works well and is a nice addition. Further cases, that we might find, can be added in follow up PRs. 🙂

**Comment by atj** [comment]
Thanks for all your help on this!
