### ISSUE TITLE
mb_spotify_isrc_link: wildcard in protocol doesn't work in Greasemonkey

### ISSUE THREAD

**Issue by ToadKing** [atj/userscripts#6]
On Greasemonkey for Firefox, installing the Spotify ISRC link script fails with the following error:

    Ignoring @match pattern http*://*.musicbrainz.org/release/* because: Error: @match: Invalid protocol (http*:) specified.

Manually adding two patters, one for http and one for https, allows it to install.

**Comment by atj** [comment]
Sorry about the lack of response to this @ToadKing. For some reason I wasn't watching this repository and so I didn't notice you'd filed an issue. Thanks for taking the time, it is appreciated.

The PR from @jesus2099 that will be merge shortly should resolve this issue.

**Comment by jesus2099** [comment]
Good spot, @ToadKing, `//@ match http*://` is invalid syntax anyway, `//@ match *://` should be used per [specs](https://developer.chrome.com/extensions/match_patterns): 

> _If the **scheme**_ [protocol] _is `*`, then it matches either `http` or `https`, and **not** `file`, or `ftp`._
